output_dir: /mnt/BRData/plex/music

artists:
  - name: Grateful Dead
    search_query: "creator:Grateful Dead AND avg_rating:[5 TO null] AND downloads:[18000 TO null]"
    sources: [SBD, FM]

  - name: Jerry Garcia Band
    search_query: "collection:taperssection creator:Jerry Garcia AND downloads:[100 TO null]"
    sources: [SBD, FM]
    date_range: ["1970-01-01","1988-12-31"]

  - name: RatDog
    collections:
      - RatDog
    sources: [SBD, FM]

  - name: Steve Kimock
    search_query: "creator:(Steve Kimock) AND avg_rating:[5 TO null] AND downloads:[4000 TO null]"
    sources: [SBD, FM, AUD]
  
  - name: KVHW
    collections:
      - KVHW
    sources: [SBD, FM, AUD]

  - name: Medeski Martin & Wood
    search_query: "creator:Medeski, Martin Wood AND downloads:[100 TO null]"
    sources: [SBD, FM, AUD]

  - name: Galactic
    search_query: "collection:GalacticFunk AND downloads:[200 TO null]"
    sources: [SBD, FM, AUD]

  - name: String Cheese Incident
    collections:
      - StringCheeseIncident
    sources: [SBD, FM]

  - name: Widespread Panic
    collections:
      - WidespreadPanic
    sources: [SBD, FM]

  - name: Zero
    collections:
      - Zero
    sources: [SBD, FM, AUD]
